apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service2
  description: This is yet another demo service
  tags:
    - nodejs
    - backend
    annotations:
      sonarqube.org/project-key: sqp_5c58e2ce10ad1ada811475645efcf5d420ce7cf8
spec:
  type: service
  lifecycle: staging
  owner: team2
